### ISSUE TITLE
Running program "bash scripts/mc_data.sh" error

### ISSUE THREAD

**Issue by xdmdtz123** [zhaoyu-li/NSNet#1]
Dear author：
  There is no problem running program "bash scripts/sat_data.sh", but when program runs to these two lines in "bash scripts/mc_data.sh", the following error will occur：
![image](https://user-images.githubusercontent.com/61136601/203005743-5cfcac98-1b4a-4ec5-95da-39ce90bc061c.png)
![image](https://user-images.githubusercontent.com/61136601/203005951-3f0bf1b9-4fb6-4bef-93c0-1f91a3104fd7.png)
  Looking forward to your reply, thank you.

**Comment by zhaoyu-li** [comment]
Hi,

Thanks for your interest. To use the DSHARP solver in our codebase, one needs to install the GMP library by:

``` bash
sudo apt-get install libgmp3-dev
```

If you feel struggle with the installation of the GMP library (or there is still something wrong with the DSHARP in our codebase), you may go to the Git Repo of [DSHARP](https://github.com/QuMuLab/dsharp) to install it by yourself (with/without GMP) and move the executable file to the same location as ours.

BTW, if you choose to install DSHARP without GMP, you also need to uncomment this [line](https://github.com/zhaoyu-li/NSNet/blob/main/src/utils/solvers.py#L82) to use it. However, DSHARP without GMP can only give an approximate model counting rather than the exact one. So I recommend you use DSHARP with GMP.

Hope this may help you.

**Comment by xdmdtz123** [comment]
I recompiled 'dsharp' according to your prompts. The program runs normally. Thanks for your help!
